### ISSUE TITLE
Clear use cases

### ISSUE THREAD

**Issue by ccurtis7** [emissible/SPEEDCOM#1]
Your use cases in the current format are difficult to parse out for someone who has no background information about your project. I would consider adding a little background before jumping into your use cases, the organizing your use cases hierarchically (which you have begin to do), with descriptions of both inputs and outputs, as described in the Software Design lecture. 

And I would also consider putting your use cases in a MarkDown file, as this will help with readability.

**Comment by jwa7** [comment]
Background information added and use cases presented in a markdown file. Thanks for the advice @ccurtis7 :)
