### ISSUE TITLE
Project pre-review

### ISSUE THREAD

**Issue by dacb** [emissible/SPEEDCOM#18]
This is looking really nice.   Good working resolving the pep8 things I mentioned on Thu. 

A few things I noticed:

- [x] Check your `.gitignore` - see things like `.DS_Store` which is a mac thing that should be in your ignore file.  

- [x] Your installation instructions should probably be `pip` not `conda` or `python setup.py install`. Minor change but... If you have a UI, you can put a screenshot in the README.md to entice visitors.  

- [ ] Your build is failing and coverage is unknown.  Not a big deal at the moment, but it would be nice if you could fix that up by Friday 9 AM.

- [x] Please add your use cases, component sketch, tech review presentation and final poster to the doc directory.

- [x] I notice some .html, .json, .hdf5, .csv and .ipynb files in the python package itself.  Maybe the data files should go into a data subdirectory or at the top level as you see fit.  Some cleanup here is still necessary.

- [x] Overall the tests are a very good start.  There are some missing comments to say what individual tests are doing and some tests that are commented out and maybe should be removed or fixed.

This is looking really great speedcommies!

**Comment by jwa7** [comment]
Just travis build left to get passing, raised in a spearate issue.

**Comment by jwa7** [comment]
Thanks for your advice @dacb !
